#ifndef WEDNESDAY_WTF_TRACE_TYPE_HPP
#define WEDNESDAY_WTF_TRACE_TYPE_HPP
namespace sdk
{
	enum trace_type {
		TRACE_EVERYTHING = 0,
		TRACE_WORLD_ONLY,
		TRACE_ENTITIES_ONLY,
		TRACE_EVERYTHING_FILTER_PROPS,
	};
} // namespace sdk
#endif // WEDNESDAY_WTF_TRACE_TYPE_HPP
